databaseType = "PostgreSql"
id = "327008ba-9026-43a2-a12c-a7d8c624db70"
name = "Air It"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.target1]
url = "jdbc:postgresql://database-server-atishay.postgres.database.azure.com:5432/youtube_data"
schemas = [ "public" ]
displayName = "Azure Postgre SQL"
